[project]
name = 'Sustainable-Fishing-Certification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.catch-documentation]
path = 'contracts/catch-documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.processing-verification]
path = 'contracts/processing-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.sustainability-certification]
path = 'contracts/sustainability-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.vessel-registration]
path = 'contracts/vessel-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
